services:
  site1:
    container_name: site1
    build: ./site1
    ports:
      - "5001:80"
    
  site2:
    container_name: site2
    build: ./site2
    ports:
      - "5002:80"

  site3:
    container_name: site3
    build: ./site3
    ports:
      - "5003:80"