FROM nginx 

RUN apt update -y
RUN apt upgrade -y
RUN apt install git -y

WORKDIR /usr/share/nginx/html/
RUN rm -rf ./*
RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube.git .

EXPOSE 80

CMD ["nginx","-g","daemon off;"]